Sana/Models/ProductListViewModel.cs
using System.Collections.Generic;
using Sana.Db.Model;

namespace Sana.Models
{
    public class ProductListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
    }
}

Sana/Models/ProductViewModel.cs
using System.ComponentModel.DataAnnotations;
using Sana.CustomValidation;
using Sana.Db.Model;

namespace Sana.Models
{
    public class ProductViewModel
    {
        [Required(ErrorMessage = "{0} cannot be empty")]
        public int Id { get; set; }

        [Required(ErrorMessage = "{0} cannot be empty")]
        [StringLength(128)]
        public string Title { get; set; }

        [Required(ErrorMessage = "{0} cannot be empty")]
        [DataType(DataType.Currency)]
        [PositiveNumber]
        public decimal Price { get; set; }

        public ProductViewModel(Product product)
        {
            Id = product.Id;
            Title = product.Title;
            Price = product.Price;
        }

        public ProductViewModel() { }

        public Product Product => new Product() { Id = Id, Title = Title, Price = Price };
    }
}

Sana/Controllers/BaseController.cs
using System.Web.Mvc;
using System.Web.Routing;
using Sana.Db;
using Sana.Db.Model;

namespace Sana.Controllers
{
    public class BaseController : Controller
    {
        protected IRepository<Product, int> Repository { get; private set; }

        public bool IsInMemory => (bool) HttpContext.Application["IsInMemory"];

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);

            if ((bool)HttpContext.Application["IsInMemory"])
                Repository = (IRepository<Product, int>)HttpContext.Application["Repository"];
            else
            {
                var ctx = new DbContext<Product>(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString);
                Repository = new ProductRepository(ctx);
            }
        }
    }
}

Sana/Controllers/PersistenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sana.Controllers
{
    public class PersistenceController : BaseController
    {
        // GET: Persistence
        public ActionResult Change()
        {
            HttpContext.Application["IsInMemory"] = !(bool)HttpContext.Application["IsInMemory"];

            return RedirectToAction("Index", "Product");
        }
    }
}

Sana/Controllers/ProductController.cs
using System.Web.Mvc;
using Sana.Db.Model;
using Sana.Models;

namespace Sana.Controllers
{
    public class ProductController : BaseController
    {
        public ActionResult Index(bool? error)
        {
            if (error.HasValue)
                ViewBag.HasError = error.Value;

            var productListviewModel = new ProductListViewModel()
            {
                Products = Repository.All()
            };
            return View(productListviewModel);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var product = Repository.Get(id);

            if (product == default(Product)) return HttpNotFound();

            return View(new ProductViewModel(product));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductViewModel product)
        {
            if (!ModelState.IsValid) return View(product);

            var result = Repository.Update(product.Product);

            return RedirectToAction(nameof(Index), new { error = !result });
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new ProductViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel product)
        {
            if (!ModelState.IsValid) return View(product);

            var result = Repository.Create(product.Product);

            return RedirectToAction(nameof(Index), new { error = !result });
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var product = Repository.Get(id);

            if (product == default(Product)) return HttpNotFound();

            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var result = Repository.Delete(id);
            return RedirectToAction(nameof(Index), new { error = !result });
        }
    }
}

Sana/Views/Product/Create.cshtml
@model Sana.Models.ProductViewModel

@{
    ViewBag.Title = "New Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Product</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sana/Views/Product/Delete.cshtml
@model Sana.Db.Model.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Sana/Views/Product/Edit.cshtml
@model Sana.Models.ProductViewModel

@{
    ViewBag.Title = "Update Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product Code - @Model.Id</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sana/Views/Product/Index.cshtml
@model Sana.Models.ProductListViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Products</h2>

@if (ViewBag.HasError != null)
{
    if (ViewBag.HasError)
    {
        <p class="alert-danger">Error saving</p>
    }
    else
    {
        <p class="alert-success">Saved correctly!</p>
    }
}

<p>
    @Html.ActionLink("Create New Product", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Code
        </th>
        <th>
            Title
        </th>
        <th>
            Price
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Products) {
    <tr>
        <td>
            @item.Id
        </td>
        <td>
            @item.Title
        </td>
        <td>
            @item.Price
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
            @Html.ActionLink("Delete", "Delete", new {id = item.Id})
        </td>
    </tr>
}

</table>

Sana/Views/Shared/_Layout.cshtml
@using Sana.Controllers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sana", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div style="float: right;">
            @using (Html.BeginForm("Change", "Persistence", FormMethod.Post))
            {
                <p class="alert-info">Current Storage: @((ViewContext.Controller as BaseController).IsInMemory ? "In Memory" : "LocalDB")</p>
                <input class="btn btn-primary" type="submit" value="Change Persistence Mode" />
            }
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {
            if ($('#Price').length) {
                $('#Price').rules('remove', 'number');
            }
        });

    </script>
</body>
</html>